name: Build Asuswrt-ipq6018

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'target to build'
        options:
        - RT-360V6
        - RT-AX18
        - RT-AX5
        - RT-W212X
        default:
          RT-360V6
      uploadanon:
        type: boolean
        description: 'upload firmware to anonfiles'
        default: 'false'
env:
  REPOSITORY_URL: https://github.com/stkuroneko/asuswrt-ipq6018.git
  TOOLCHAINS_URL: https://github.com/SWRT-dev/qca-toolchains.git
  WORK_PATH: /home/runner/work
  SRC_PATH: /home/runner/work/asuswrt-ipq6018
  TOOLCHAINS_PATH: /home/runner/work/qca-toolchains
  TIME_ZONE: Asia/Shanghai
  FIRMWARE_PATH: /home/runner/work/firmwares
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev \
        patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core \
        gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev \
        autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget libncurses5:i386 \
        libelf1:i386 lib32z1 lib32stdc++6 gtk-doc-tools intltool binutils-dev cmake lzma liblzma-dev lzma-dev \
        uuid-dev liblzo2-dev xsltproc dos2unix libstdc++5 docbook-xsl-* sharutils autogen shtool gengetopt \
        libltdl-dev libtool-bin bison
        sudo timedatectl set-timezone "$TIME_ZONE"
    - name: Clone source code
      run: |
        git clone --depth=1 $REPOSITORY_URL $SRC_PATH
        git clone --depth=1 $TOOLCHAINS_URL $TOOLCHAINS_PATH
    - name: Build
      run: |
        sudo cp -f scripts/build_ipq6018.sh $WORK_PATH/build.sh
        cd $WORK_PATH
        sudo chmod 777 ./build.sh
        bash ./build.sh ${{ github.event.inputs.target }}
    - name: Organize firmware files
      run: |
        mkdir -p $FIRMWARE_PATH/
        cd $SRC_PATH/release/src-qca-cypress/image
        for firmwarefile in $(ls *.trx)
        do sudo mv $firmwarefile $FIRMWARE_PATH/$firmwarefile
        done
        cd $FIRMWARE_PATH
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "STATUS=success" >> $GITHUB_ENV
    - name : Upload packages
      uses: actions/upload-artifact@main
      if: env.STATUS == 'success'
      with:
        name: Asuswrt-ipq6018-packages
        path: ${{ env.FIRMWARE }}
    - name: Upload firmware to anonfiles
      if: env.STATUS == 'success' && github.event.inputs.uploadanon == 'true'
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer anon --no-progress ${FIRMWARE} 2>&1 | tee anonfile.log
        echo "::warning file=anonfile.com::$(cat anonfile.log | grep -o -E "https?://[a-zA-Z0-9\.\/_&=@$%?~#-]*")"
    - name: Remove obsolete firmwares on artifacts
      uses: c-hive/gha-remove-artifacts@v1.3.0
      if: env.STATUS == 'success'
      with:
        age: '1 day'
        skip-recent: 5
